### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY:

### ISSUE THREAD

**Issue by miraliahmadli** [aws-deepracer-community/deepracer-for-dummies#13]
```
## Creating agent - name: agent
Traceback (most recent call last):
  File "training_worker.py", line 252, in <module>
    main()
  File "training_worker.py", line 247, in main
    memory_backend_params=memory_backend_params
  File "training_worker.py", line 68, in training_worker
    graph_manager.create_graph(task_parameters)
  File "/usr/local/lib/python3.6/dist-packages/rl_coach/graph_managers/graph_manager.py", line 153, in create_graph
    self.create_session(task_parameters=task_parameters)
  File "/usr/local/lib/python3.6/dist-packages/rl_coach/graph_managers/graph_manager.py", line 254, in create_session
    self._create_session_tf(task_parameters)
  File "/usr/local/lib/python3.6/dist-packages/rl_coach/graph_managers/graph_manager.py", line 238, in _create_session_tf
    self.sess = tf.Session(config=config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1511, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 634, in __init__
    self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 2097479680
```

I am getting this error. Does anyone know how to solve it?

**Comment by ericconnelly** [comment]
I'm new to this, too, but I believe your graphics card has only 2gb of memory (total memory reported: 2097479680). I think the error is because the card ran out of memory to store the training set it's working on. I don't know if there is a workaround. I read that 8+gb cards are best for tensorflow training. What is your current machine?

**Comment by larsll** [comment]
Outdated issue. No activity. Closing.
